account/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import *


app_name='account'
urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

magazine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('main.urls')),
    path('account/', include('account.urls', namespace='account')),
]

main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import *


urlpatterns = [
    path('', HomeMain.as_view(), name='home'),
    path('catalog/', CatalogMain.as_view(), name='catalog'),
    path('catalog/<slug:cat_slug>', ProductList.as_view(), name='cat_slug'),
    path('prod/<slug:prod_slug>/', ProductDetail.as_view(), name='prod'),
    path('about/', about, name='about'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    title = models.CharField(max_length=255, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    content = models.TextField(blank=True, verbose_name="Описание")
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name="Фото")
    price = models.IntegerField(default=True, verbose_name='Цена')
    stock = models.PositiveIntegerField(null=True)
    is_published = models.BooleanField(default=True, verbose_name="Публикация")
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name="Категории")

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['id']
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('prod', kwargs={'prod_slug': self.slug})


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name="Категория")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cat_slug', kwargs={'cat_slug': self.slug})

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

account/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import LoginUserForm, RegisterUserForm
from .utils import *


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'account/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация'
        return context

    def get_success_url(self):
        return reverse_lazy('home')


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'account/registration.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Регистрация")
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


def logout_user(request):
    logout(request)
    return redirect('home')

cart/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from main.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth import authenticate, login

from cart.forms import CartAddProductForm

from .models import *


class HomeMain(ListView):
    model = Category
    template_name = 'main/home.html'
    context_object_name = 'category'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная страница'
        return context


class CatalogMain(ListView):
    model = Category
    template_name = 'main/product/catalog.html'
    context_object_name = 'category'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = Product.objects.filter(is_published=True)
        context['title'] = 'Каталог'
        return context

    def get_queryset(self):
        return Category.objects.all()


class ProductList(ListView):
    model = Category
    template_name = 'main/product/catalog.html'
    context_object_name = 'category'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = Product.objects.filter(cat__slug=self.kwargs['cat_slug'], is_published=True)
        context['title'] = 'Каталог'
        return context

    def get_queryset(self):
        return Category.objects.all()


class ProductDetail(DetailView):
    model = Product
    template_name = 'main/product/post.html'
    slug_url_kwarg = 'prod_slug'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_product_form'] = CartAddProductForm()
        context['title'] = context['product']
        return context


def about(request):
    return render(request, 'main/about.html')

cart/templates/cart/detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block body %}
    <h1 class="korzina-title">Корзина твоих товаров</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Фото</th>
            <th>Товар</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Цена шт.</th>
            <th>Общая стоимость заказа</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img class="img-card"src="{{ product.photo.url }}">
                        </a>
                    </td>
                    <td>{{ product.title }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Общая</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'catalog' %}" class="button light">Продолжить покупки</a>
        <a href="#" class="button">Купить</a>
    </p>
{% endblock %}

main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}


{% block body %}
<h1>Информация о сайте</h1>
<div class="container-info">
    <h3>Здесь можно предоставлять полный список адресов.</h3>

    <ul>
        <li>Адрес 1</li>
        <li>Адрес 2</li>
        <li>Адрес 3</li>
        <li>Адрес 4</li>
    </ul>
</div>
{% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;500;700&display=swap" rel="stylesheet">
    <script src="{% static 'main/js/javascripts.js' %}"></script>
    <title>{{ title }}</title>
</head>
<body>
    <div class="topnav">
        <div class="left_nav">
            <a href="{% url 'home' %}">Главная</a>
            <a href="{% url 'catalog' %}">Каталог</a>
        </div>

        <div class="center_nav">
            <img src="{% static 'main/images/logo.png' %}" alt="no img">
        </div>

        <div class="right_nav">
            <a href="{% url 'about' %}">Информация</a>
            <a href="{% url 'cart:cart_detail' %}">Корзина</a>
        </div>

        <div class="account_nav">
            {% if request.user.is_authenticated %}
            <li class="last"> {{user.username}} | 
                <a href="{% url 'account:logout' %}">Выйти</a></li>
            {% else %}
            <li class="last"><a href="{% url 'account:register' %}">Регистрация</a> | 
                <a href="{% url 'account:login' %}">Войти</a></li>
            {% endif %}
        </div>
    </div>


{% block body %}



{% endblock %}

    <div class="bottomnav">
        <div class="left">
            <p>information for my website</p>
        </div>
        <div class="right">
            <a href="#"><img src="" alt=""></a>
            <a href="#"><img src="" alt=""></a>
            <a href="#"><img src="" alt=""></a>
            <a href="#"><img src="" alt=""></a>
        </div>
    </div>    
</body>
</html>

main/templates/main/catalog.html
{% extends 'main/base.html' %}
{% load static %}



{% block body %}

    <h2>Каталог товаров</h2>


    <div class="flex_nav">
        <ul class="category_nav">
            <li><a href="{% url 'catalog' %}">Все категории</a></li>
            {% for c in category %}
            <li><a href="/catalog/{{ c.slug }}">{{ c.name }}</a></li>
            {% endfor %}
        </ul>
    </div>  

    <div class="flex_content">
        {% for p in product %}
            <div class="card">
                <img src="{{ p.photo.url }}" alt="Карточка товара" style="width:100%">
                <h1>{{ p.title }}</h1>
                <p class="card_content">{{ p.content }}</p>
                <p class="price">цена: {{ p.price }}</p>
                <p><a href="{{ p.get_absolute_url }}"><button>Узнать больше</button></a></p>
            </div>
        {% endfor %}
    </div> 

{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}


{% block body %}

    <!-- Контейнер слайд-шоу -->
    <div class="slideshow-container">

        <!-- Полноразмерные изображения с числом и текстом подписи -->
        <div class="mySlides fade" style="display: block;">
            <img src="{% static 'main/images/img1.jpg' %}" style="width:100%">
            <div class="text">Подпись текст</div>
        </div>
    
        <div class="mySlides fade">
            <img src="{% static 'main/images/img2.jpg' %}" style="width:100%">
            <div class="text">Подпись два</div>
        </div>
    
        <div class="mySlides fade">
            <img src="{% static 'main/images/img3.jpg' %}" style="width:100%">
            <div class="text">Подпись три</div>
        </div>

        <div class="mySlides fade">
            <img src="{% static 'main/images/img4.jpg' %}" style="width:100%">
            <div class="text">Подпись три</div>
        </div>
    
        <!-- Вперед и назад кнопки -->
        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>
    </div>
    <br>
    
    <!-- Точки/круги -->
    <div style="text-align:center">
        <span class="dot" onclick="currentSlide(1)"></span>
        <span class="dot" onclick="currentSlide(2)"></span>
        <span class="dot" onclick="currentSlide(3)"></span>
        <span class="dot" onclick="currentSlide(4)"></span>
    </div>

    <h2>информация</h2>

    <div class="information">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            Deleniti aperiam atque quisquam est aspernatur, odio officiis repudiandae voluptas ut, 
            id dolorum accusantium blanditiis inventore? Saepe iure tempora tempore non facere?</p>
    </div>


    <h2>Готовые наборы</h2>

    <div class="row">
        <div class="column">
            <img src="#" alt="">
            <div class="column_title">
                <h3>Кольцевая</h3>
            </div>
            <div class="column_content">
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. 
                    Repudiandae laudantium earum, voluptas consequatur fuga modi. Magni vitae inventore ab, 
                    expedita doloribus similique obcaecati deserunt provident natus suscipit molestias, 
                    dolorum aperiam.С мостамиС мостами</p>
            </div>
        </div>
        <div class="column">
            <img src="#" alt="">
            <div class="column_title">
                <h3>Бесконечная</h3>
            </div>
            <div class="column_content">
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. 
                    Repudiandae laudantium earum, voluptas consequatur fuga modi. Magni vitae inventore ab, 
                    expedita doloribus similique obcaecati deserunt provident natus suscipit molestias, 
                    dolorum aperiam.С мостамиС мостами</p>
            </div>
        </div>
        <div class="column">
            <img src="#" alt="">
            <div class="column_title">
                <h3>С мостами</h3>
            </div>
            <div class="column_content">
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. 
                    Repudiandae laudantium earum, voluptas consequatur fuga modi. Magni vitae inventore ab, 
                    expedita doloribus similique obcaecati deserunt provident natus suscipit molestias, 
                    dolorum aperiam.С мостамиС мостами</p>
            </div>
        </div>
        <div class="column">
            <img src="#" alt="">
            <div class="column_title">
                <h3>С Инфаструктурой</h3>
            </div>
            <div class="column_content">
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. 
                    Repudiandae laudantium earum, voluptas consequatur fuga modi. Magni vitae inventore ab, 
                    expedita doloribus similique obcaecati deserunt provident natus suscipit molestias, 
                    dolorum aperiam.С мостамиС мостами</p>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/post.html
{% extends 'main/base.html' %}

{% block body %}

<div class="post_title">
    <h1>{{ post.title }}</h1>
</div>

<div class="post_container">

    <div class="post_image">
        <img src="{{ post.photo.url }}">
    </div>

    <div class="post_content">
        <h4>Описание товара: </h4>
        <p>{{post.content}}</p>
    </div>

    <div class="post_dop_content">
        <ul>
            <h4>Доп. описание товара: </h4>
            <li>Доп.1:</li>
            <li>Доп.1:</li>
            <li>Доп.1:</li>
        </ul>
    </div>
</div>

{% endblock %}

main/templates/main/product/catalog.html
{% extends 'main/base.html' %}
{% load static %}



{% block body %}

    <h2>Каталог товаров</h2>


    <div class="flex_nav">
        <ul class="category_nav">
            <li><a href="{% url 'catalog' %}">Все категории</a></li>
            {% for c in category %}
            <li><a href="/catalog/{{ c.slug }}">{{ c.name }}</a></li>
            {% endfor %}
        </ul>
    </div>  

    <div class="flex_content">
        {% for p in product %}
            <div class="card">
                <img src="{{ p.photo.url }}" alt="Карточка товара" style="width:100%">
                <h1>{{ p.title }}</h1>
                <p class="card_content">{{ p.content }}</p>
                <p class="price">${{ p.price }}</p>
                <p><a href="{{ p.get_absolute_url }}"><button>Узнать больше</button></a></p>
            </div>
        {% endfor %}
    </div> 

{% endblock %}

main/templates/main/product/post.html
{% extends 'main/base.html' %}

{% block body %}

<div class="post_title">
    <h1>{{ product.title }}</h1>
</div>

<div class="post_container">

    <div class="post_image">
        <img src="{{ product.photo.url }}">
    </div>

    <div class="post_content">
        <h4>Описание товара: </h4>
        <p>{{product.content}}</p>
    </div>

    <div class="post_dop_content">
        <ul>
            <h4>Доп. описание товара: </h4>
            <li>Доп.1:</li>
            <li>Доп.1:</li>
            <li>Доп.1:</li>
        </ul>
    </div>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
    </form>
</div>

{% endblock %}